version: '3.7'

services:

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./messaging/repository/preparekeyspace/cassandra_chat_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 100 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  app:
    build: .
    container_name: "chat"
    env_file:
      - .env
    depends_on:
      - cassandra-load-keyspace
    environment:
      DB_HOST: "cassandra"
      DB_PORT: "9042"
    ports:
      - "8080:8080"
    volumes:
      - .:/chat
