// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendSimpleMail provides a mock function with given fields: to, body
func (_m *Mailer) SendSimpleMail(to string, body []byte) error {
	ret := _m.Called(to, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(to, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
