// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	cassandra "chat/messaging/repository/cassandra"
	context "context"

	gocql "github.com/gocql/gocql"

	mock "github.com/stretchr/testify/mock"
)

// BatchInterface is an autogenerated mock type for the BatchInterface type
type BatchInterface struct {
	mock.Mock
}

// AddBatchEntry provides a mock function with given fields: entry
func (_m *BatchInterface) AddBatchEntry(entry *gocql.BatchEntry) {
	_m.Called(entry)
}

// WithContext provides a mock function with given fields: ctx
func (_m *BatchInterface) WithContext(ctx context.Context) cassandra.BatchInterface {
	ret := _m.Called(ctx)

	var r0 cassandra.BatchInterface
	if rf, ok := ret.Get(0).(func(context.Context) cassandra.BatchInterface); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.BatchInterface)
		}
	}

	return r0
}
