// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	cassandra "chat/messaging/repository/cassandra"

	mock "github.com/stretchr/testify/mock"
)

// IterInterface is an autogenerated mock type for the IterInterface type
type IterInterface struct {
	mock.Mock
}

// Scanner provides a mock function with given fields:
func (_m *IterInterface) Scanner() cassandra.ScannerInterface {
	ret := _m.Called()

	var r0 cassandra.ScannerInterface
	if rf, ok := ret.Get(0).(func() cassandra.ScannerInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cassandra.ScannerInterface)
		}
	}

	return r0
}
